#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################## ${LP}DESCRIPTIONS${NC} #########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=Vigna-angularis-description
./gradlew integrate --stacktrace -Psource=Vigna-radiata-description
./gradlew integrate --stacktrace -Psource=Vigna-unguiculata-description

./gradlew integrate --stacktrace -Psource=aradu-description
./gradlew integrate --stacktrace -Psource=araip-description
./gradlew integrate --stacktrace -Psource=cajca-description
./gradlew integrate --stacktrace -Psource=glyma-description
./gradlew integrate --stacktrace -Psource=lotja-description
./gradlew integrate --stacktrace -Psource=lupan-description
./gradlew integrate --stacktrace -Psource=medtr-description
./gradlew integrate --stacktrace -Psource=phavu-description
