#!/bin/sh

NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "############################ ${LP}MARKERS${NC} ############################"
echo -e "#################################################################"

## vigra
./gradlew integrate --stacktrace -Psource=VC1973A.gnm6.mrk.microsatellites
./gradlew integrate --stacktrace -Psource=VC1973A.gnm6.mrk.Sandhu_Singh_2020

## vigun
./gradlew integrate --stacktrace -Psource=IT97K-499-35.gnm1.mrk.Cowpea1MSelectedSNPs
