#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "############################ ${LP}MAP${NC} ################################"
echo -e "#################################################################"

## vigun
./gradlew integrate --stacktrace -Psource=iSelect-consensus-2016.map.Munoz-Amatriain_Mirebrahim_2017
./gradlew integrate --stacktrace -Psource=MAGIC-2017.map.Huynh_Ehlers_2018
