#!/bin/sh

rm -f validate-expression.md
touch validate-expression.md


validate-expression-collection /data/v2/Vigna/unguiculata/expression/IT97K-499-35.gnm1.ann1.expr.BWH5 >> validate-expression.md

