#!/bin/sh

rm -f validate-markers.md
touch validate-markers.md

## vigra
validate-marker-collection /data/v2/Vigna/radiata/markers/VC1973A.gnm6.mrk.microsatellites >> validate-markers.md
validate-marker-collection /data/v2/Vigna/radiata/markers/VC1973A.gnm6.mrk.Sandhu_Singh_2020 >> validate-markers.md

## vigun
validate-marker-collection /data/v2/Vigna/unguiculata/markers/IT97K-499-35.gnm1.mrk.Cowpea1MSelectedSNPs >> validate-markers.md

