#!/bin/sh
echo "********** cowpeamine/integrate **********"
ant clean

## ontologies
#ant -v -Dsource=go,so,po
#ant -v -Dsource=to
#ant -v -Dsource=co

## chado loaders
#ant -v -Dsource=chado-genomics
#ant -v -Dsource=chado-genetics
#ant -v -Dsource=chado-featureprop,chado-genefamilies,chado-homology

#pg_restore -d cowpeamine /home/shokin/dumps/cowpeamine.chado.dat

#############################################################################################
# ALL of the chado loaders must be DONE above, because identifiers are changed by SQL below #
#############################################################################################

#psql cowpeamine -f ../dbmodel/build/model/add-update-triggers.sql
#psql cowpeamine -f ../sql/cleanup-chado-bugs.sql
#psql cowpeamine -f ../sql/update-organism-genus-species.sql
#psql cowpeamine -f ../sql/update-organism-descriptions.sql
#psql cowpeamine -f ../sql/update-identifiers.sql
#psql cowpeamine -f ../dbmodel/build/model/remove-update-triggers.sql

## file loaders
#ant -v -Dsource=cowpea-germplasms
#ant -v -Dsource=cowpea-snpmarkers
#ant -v -Dsource=cowpea-snppositions
#ant -v -Dsource=cowpea-linkagegroups
#ant -v -Dsource=cowpea-markers-linkagegroups
#ant -v -Dsource=cowpea-genotypes
#ant -v -Dsource=cowpea-qtls
#ant -v -Dsource=cowpea-markers-qtls
#ant -v -Dsource=cowpea-qtl-trait-ontology
#ant -v -Dsource=cowpea-qtl-crop-ontology
#ant -v -Dsource=cowpea-expression

## update the genus and species for the germplasms we added, don't touch the descriptions!
psql cowpeamine -f ../dbmodel/build/model/add-update-triggers.sql
psql cowpeamine -f ../sql/update-organism-genus-species.sql
psql cowpeamine -f ../dbmodel/build/model/remove-update-triggers.sql
